### ISSUE TITLE
关于a13澎湃的一些问题

### ISSUE THREAD

**Issue by LAOBILAXI233** [HChenX/ForegroundPin#2]
在k40g基于a13的澎湃os环境上某些应用（例如崩坏星穹铁道等横屏游戏）贴边后一段时间再次打开会出现打不开的情况，有打开的动画但是会被还原回贴边状态，从后台尝试打开未果，只有清除后台才能再次打开

**Comment by HChenX** [comment]
a13澎湃无法测试
